name: build-and-test
run-name: Build and Test run by @${{ github.actor }}

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Build, start services, and run tests with Docker Compose
        run: docker compose -f docker-compose-test.yml up --build --abort-on-container-exit

       
